language: go

go:
  - 1.x

before_install:
  - go get github.com/docopt/docopt-go

os:
  - linux
  - osx


deploy:
  api_key: ${GITHUB_OAUTH_KEY}
  provider: releases
  skip_cleanup: true
  draft: true